### ISSUE TITLE
Crash : UI_Orc.m2 #by Uthil

### ISSUE THREAD

**Issue by Koward** [Koward/jM2converter#2]
-jar jm2converter.jar -in UI_Orc.m2 -out UI_Orcs.m2 -cl
[[ Java M2 Converter by Koward v1.0.7-beta ]]
Model read.
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size:2
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at jm2lib.blizzard.wow.lichking.Particle.downConvert(Particle.java:339)
        at jm2lib.blizzard.wow.lichking.Model.downConvert(Model.java:366)
        at jm2lib.blizzard.wow.M2.convert(M2.java:75)
        at koward.Main.convertModel(Main.java:108)
        at koward.Main.main(Main.java:84)

**Comment by Koward** [comment]
Should be fixed with 1.0.8-beta. Now checks if alpha track is large enough. If not, default to opaque (0x7FFF).
